apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kokot-web
spec:
  rules:
    - host: kokot.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kokot-web
                port:
                  number: 80
