apiVersion: batch/v1
kind: Job
metadata:
  name: kokot-migrate
spec:
  template:
    metadata:
      labels:
        app: kokot-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: kokot-web:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate"]
          envFrom:
            - configMapRef:
                name: kokot-config
            - secretRef:
                name: kokot-secrets
